/// <reference types="koffi" />
export const XINPUT_GAMEPAD: import("koffi").IKoffiCType;
export const XINPUT_STATE: import("koffi").IKoffiCType;
export const XINPUT_VIBRATION: import("koffi").IKoffiCType;
export const XINPUT_BATTERY_INFORMATION: import("koffi").IKoffiCType;
export const XINPUT_CAPABILITIES: import("koffi").IKoffiCType;
export const XINPUT_KEYSTROKE: import("koffi").IKoffiCType;
export const XINPUT_CAPABILITIES_EX: import("koffi").IKoffiCType;
export const XINPUT_BASE_BUS_INFORMATION: import("koffi").IKoffiCType;
export const XINPUT_LISTEN_STATE: import("koffi").IKoffiCType;
export const XINPUT_VIBRATION_EX: import("koffi").IKoffiCType;
export const APP_LOCAL_DEVICE_ID: import("koffi").IKoffiCType;
